spring:
  application:
    name: hackaton-fiapx
    security:
      password-rules-exempt: false
      password-min-length: 8
      password-min-alpha-upper: 1
      password-min-alpha-lower: 1
      password-min-numeric: 1
      password-min-special: 1
      password-special-chars: "@#$%&(){}[]"
      password-expire-days: 90
  jwt:
    secret-key: ZEdocGN5MXBjeTF0ZVMxbWRXTnJhVzVuTFhObFkzSmxkQzFyWlhrdFpHOTFZMmhs
    token-expire-time: 10800000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/migration.xml