apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306