name: Docker Image CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Short commit hash
        run: echo "TC_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USER }}/fiapx-user-management:${{ env.TC_IMAGE_TAG }} -f ./Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/fiapx-user-management:${{ env.TC_IMAGE_TAG }}
      
      - name: Tag Docker Image as Latest
        run: docker image tag ${{ secrets.DOCKER_HUB_USER }}/fiapx-user-management:${{ env.TC_IMAGE_TAG }} ${{ secrets.DOCKER_HUB_USER }}/fiapx-user-management:latest

      - name: Push Docker Image as Latest
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/fiapx-user-management:latest
